#!/bin/bash

DATE=$(date +%c)

#NAGIOS_STATUS="/var/nagios/status.dat"
#NAGIOS_STATUS="/usr/local/nagios/var/status.dat"
NAGIOS_STATUS="/var/cache/nagios3/status.dat"
WORKING_DIR="/usr/local/bin"

SUBJECT="Disabled Nagios notifications on $(hostname -s) *** $DATE"
from="sender@domain.com"
SENDMAIL_FOLDER="$WORKING_DIR/sendmail"
RCPT="reciever@domain.com"


userpass="nagiosadmin:password"
nagios_server="nagios.server.yourdomain.com"

function run_awk() {
awk -v user=$userpass -v server=$nagios_server 'BEGIN { header1=0; header2=0;  FS="="; host_result_n=""; host_result_a=""; service_result_n=""; service_result_a=""; }
/^[[:space:]]*info {[[:space:]]*$/ { codeblock="info"; }
/^[[:space:]]*program {[[:space:]]*$/ { codeblock="program"; }
/^[[:space:]]*hoststatus {[[:space:]]*$/ || /^[[:space:]]*host {[[:space:]]*$/ { codeblock="host";  host_name=""; host_notifications=""; host_active=""; }
/^[[:space:]]*servicestatus {[[:space:]]*$/ || /^[[:space:]]*service {[[:space:]]*$/ { codeblock="service";  service_description=""; service_notifications=""; service_active=""; }
/^[[:space:]]*host_name=/ { host_name=$2; }
/^[[:space:]]*service_description=/ { if (codeblock=="service") { service_description=$2;} }
/^[[:space:]]*notifications_enabled=/ { if (codeblock=="service") { service_notifications=$2;  } else if (codeblock=="host") { host_notifications=$2;} }
/^[[:space:]]*active_checks_enabled=/ { if (codeblock=="service") { service_active=$2;} else if (codeblock=="host") { host_active=$2;  } }
/^[[:space:]]*}[[:space:]]*$/ {
	if (codeblock=="host") { 
		if (header1==0) {
			print "<tr><td colspan=2 bgcolor=green><b><font color=white><b>The following hosts have Notifications/Active Checks disabled:</font></b></td></tr>";
			header1=1;
		}
  		if (host_notifications=="0") { 
			print "<tr bgcolor=#CCCCCC><td>"host_name"</td><td><a href=\"http://"user"@"server"/nagios/cgi-bin/cmd.cgi?cmd_typ=28&cmd_mod=2&host="host_name"&btnSubmit=Commit\">ENABLE NOTIFICATION on "host_name"</a></td></t>";
  		}
  		if (host_active=="0") { 
			print "<tr><td>"host_name"</td><td><a href=\"http://"user"@"server"/nagios/cgi-bin/cmd.cgi?cmd_typ=47&host="host_name"&btnSubmit=Commit\">ENABLE ACTIVE CHECK on "host_name"</a></td></t>\n";
		}
		
	}
	if (codeblock=="service") { 
		if (header2==0) {
			print "<tr><td colspan=2 bgcolor=red><b><font color=white>The following services have Notifications/Active checks turned off</font></b></td></tr>";
			header2=1;
		}
  		if (service_active=="0") { 
			print "<tr><td>"service_description " on " host_name"</td><td><a href=\"http://"user"@"server"/nagios/cgi-bin/cmd.cgi?cmd_typ=5&host="host_name"&service="service_description"&btnSubmit=Commit\">ENABLE ACTIVE CHECKS</a></td></tr>";
		}
		if (service_notifications=="0") {
			print "<tr bgcolor=#CCCCCC><td>"service_description " on " host_name"</td><td><a href=\"http://"user"@"server"/nagios/cgi-bin/cmd.cgi?cmd_typ=22&cmd_mod=2&host="host_name"&service="service_description"&btnSubmit=Commit\">ENABLE SERVICE NOTIFICATION</a></td></tr>";
		}
	}
   }'
}

RESULT=$(/bin/cat $NAGIOS_STATUS| run_awk)
if [[ -n $RESULT ]]; then
  	cd $SENDMAIL_FOLDER;./sendmail.pl "$WORKING_DIR" "$from" "$RCPT" "$SUBJECT:" "<table>$RESULT</table>"
else
	echo "Nothing is disabled..."
fi 
